variables:
  # From the docs: https://docs.gitlab.com/ee/ci/yaml/#git-strategy
  #   „fetch is faster as it re-uses the project workspace (falling back
  #   to clone if it doesn't exist). git clean is used to undo any changes
  #   made by the last job, and git fetch is used to retrieve commits
  #   made since the last job ran.“
  GIT_STRATEGY: fetch
  GOOGLE_PROJECT: cw-anthos-poc
  # https://medium.com/@gajus/making-docker-in-docker-builds-x2-faster-using-docker-cache-from-option-c01febd8ef84
  # The 'latest' image. Used as a base to cache from
  # when building the $BUILD_IMAGE.

  SERVICE_NAME: otter-ly
  TLD: gke-on-prem.com

stages:
  - build
  - deploy

before_script:
  - eval export REGISTRY_URL="eu.gcr.io/$GOOGLE_PROJECT/$SERVICE_NAME"
  - eval export SHORT_GIT_SHA=$(git rev-parse --short HEAD)
  - eval export SANITIZED_BRANCH_NAME=$(echo $CI_COMMIT_REF_NAME | sed -e "s/\//-/g")
  # The image tag of this build
  - eval export BUILD_IMAGE=${REGISTRY_URL}:${SANITIZED_BRANCH_NAME}-${SHORT_GIT_SHA}
  - eval export CACHE_TAG=${REGISTRY_URL}:cache
  # The fqdn of the gitlab server is not available in the standard env vars so we cut it out of this URL
  - eval export GITLAB_HOSTNAME=$(echo $CI_PROJECT_URL | awk -F/ '{print $3}')


#########
# BUILD #
#########
build:
  stage: build
  cache:
    policy: pull
  script:
    - gcloud auth configure-docker
    - docker build
      --pull
      --tag $BUILD_IMAGE
      --cache-from $CACHE_TAG
      .

    # Push container to GitLab docker registry
    - docker push $BUILD_IMAGE
    - docker tag $BUILD_IMAGE $CACHE_TAG
    - docker push $CACHE_TAG    


##########
# REVIEW #
##########
start-review:
  stage: deploy
  environment:
    name: review-${SERVICE_NAME}
    url: http://rev-${SERVICE_NAME}--${CI_COMMIT_REF_SLUG}.${TLD}
    on_stop: stop-review
  only:
    - branches
  except:
    - master
  cache:
    policy: pull
  script:
    - cat k8s/deployment.yaml | envsubst
    - cat k8s/deployment.yaml | envsubst | kubectl apply -n $KUBE_NAMESPACE -f -

stop-review:
  stage: deploy
  environment:
    name: review-${SERVICE_NAME}
    action: stop
  when: manual
  cache:
    policy: pull
  script:
    - kubectl delete namespace $KUBE_NAMESPACE
  variables:
    GIT_STRATEGY: none
  only:
    - branches
  except:
    - master


###########
# STAGING #
###########
deploy-staging:
  stage: deploy
  environment:
    name: staging
    url: http://staging-${SERVICE_NAME}.${TLD}
  only:
    - master
  cache:
    policy: pull
  script:
    - cat k8s/deployment.yaml | envsubst
    - cat k8s/deployment.yaml | envsubst | kubectl apply -n $KUBE_NAMESPACE -f -


##############
# PRODUCTION #
##############
deploy-production:
  stage: deploy
  environment:
    name: production
    url: http://production-${SERVICE_NAME}.${TLD}
  cache:
    policy: pull
  script:
    - cat k8s/deployment.yaml | envsubst
    - cat k8s/deployment.yaml | envsubst | kubectl apply -n $KUBE_NAMESPACE -f -
  # These two 'onlys' give us AND logic. The commit should both be in master AND be tagged. NB. this is git tagging. not 'gitlab' tagging.
  only:
    - master
  only:
    - tags

